const GODBOLT_LANGUAGE_MAP: Record<string, string> = {

    c: 'c',
    'c++': 'c++',
    cpp: 'c++',
    'c++ (circle)': 'c++',
    'objective-c': 'objc',
    'objective-c++': 'objc++',
    'c++ for opencl': 'openclc',
    c3: 'c3',
    'sfpi c++': 'c++',
    'c with coccinelle': 'c',
    'c++ with coccinelle': 'c++',

    'c#': 'csharp',
    'f#': 'fsharp',
    'visual basic': 'vb',

    rust: 'rust',
    go: 'go',
    assembly: 'asm',
    fortran: 'fortran',

    java: 'java',
    kotlin: 'kotlin',
    scala: 'scala',
    clojure: 'clojure',

    'py': 'python',
    python: 'python',
    ruby: 'ruby',
    perl: 'perl',
    lua: 'lua',
    javascript: 'javascript',
    typescript: 'typescript',
    'typescript native': 'typescript',

    haskell: 'haskell',
    ocaml: 'ocaml',
    erlang: 'erlang',
    racket: 'racket',
    raku: 'raku',
    clean: 'clean',
    lean: 'lean',
    'llvm tablegen': 'tablegenbe',

    ada: 'ada',
    pascal: 'pascal',
    d: 'd',
    nim: 'nim',
    crystal: 'crystal',
    dart: 'dart',
    julia: 'julia',
    zig: 'zig',
    swift: 'swift',
    v: 'v',
    vala: 'vala',
    odin: 'odin',
    pony: 'pony',
    carbon: 'carbon',
    cobol: 'cobol',
    mojo: 'mojo',
    nix: 'nix',
    hylo: 'hylo',
    hook: 'hook',
    spice: 'spice',
    snowball: 'snowball',
    slang: 'slang',
    sail: 'sail',
    solidity: 'solidity',
    'yul (solidity ir)': 'yul',
    vyper: 'vyper',
    sway: 'sway',
    hlsl: 'hlsl',
    glsl: 'glsl',
    ispc: 'ispc',
    'cuda c++': 'cuda',
    triton: 'triton',
    'cute dsl': 'cuda',
    mlir: 'mlir',
    circt: 'circt',
    'llvm ir': 'llvmir',
    'llvm mir': 'llvmmir',
    'spir-v': 'spirv',
    wasm: 'wasm',
    ptx: 'ptx',
    il: 'il',
    gimple: 'gimple',
    co2: 'co2',
    ygen: 'ygen',
    'android java': 'java',
    'android kotlin': 'kotlin',
    cppx: 'cppx',
    'cppx-blue': 'cppx-blue',
    'cppx-gold': 'cppx-gold',
    'cpp2-cppfront': 'cpp2',
    helion: 'helion',
    algol68: 'algol68',
    'modula-2': 'modula2',
    razorforge: 'razorforge',
    numba: 'numba',
    analysis: 'analysis',
    cmakescript: 'cmake',
    'opencl c': 'openclc',
    'llvm tablegenbe': 'tablegenbe',
};

const GODBOLT_EXCLUDED_LANGUAGES = new Set([
    'hlsl',
    'glsl',
    'slang',
    'cuda c++',
    'opencl c',
    'c++ for opencl',
    'ispc',
    'triton',
    'cute dsl',
    'llvm ir',
    'llvm mir',
    'mlir',
    'circt',
    'ptx',
    'spir-v',
    'wasm',
    'il',
    'gimple',
    'co2',
    'ygen',
    'android java',
    'android kotlin',
    'solidity',
    'yul (solidity ir)',
    'vyper',
    'sway',
    'cmakescript',
    'llvm tablegen',
    'analysis',
    'sail',
    'c with coccinelle',
    'c++ with coccinelle',
    'numba',
    'razorforge',
]);

export function getGodboltLanguageId(displayLanguage: string): string | null {
    const key = displayLanguage.toLowerCase().trim();
    if (GODBOLT_EXCLUDED_LANGUAGES.has(key)) return null;
    return GODBOLT_LANGUAGE_MAP[key] ?? null;
}

const GODBOLT_DEFAULT_COMPILER: Record<string, string> = {
    'c++': 'g142',
    c: 'g142',
    'objc++': 'g142',
    objc: 'g142',
    'openclc': 'g142',
    c3: 'c3trunk',
    cuda: 'nvcc1240',
    csharp: 'dotnet901csc',
    fsharp: 'dotnet901fsc',
    vb: 'dotnet901vbc',
    java: 'java2300',
    kotlin: 'kotlinc2010',
    scala: 'scalac3310',
    clojure: 'clj1120',
    rust: 'r1870',
    go: 'go1230',
    zig: 'z0140',
    swift: 'swift600',
    ada: 'gnat142',
    fortran: 'gfortran142',
    d: 'ldc1400',
    pascal: 'fpc332',
    nim: 'nim2020',
    crystal: 'crystal181',
    odin: 'odinlatest',
    v: 'vtrunk',
    vala: 'valatrunk',
    pony: 'ponylatest',
    carbon: 'carbontrunk',
    cobol: 'gnucobol36',
    python: 'python312',
    ruby: 'ruby340',
    perl: 'perl540',
    lua: 'lua544',
    javascript: 'node220',
    typescript: 'tsc540',
    haskell: 'ghc966',
    ocaml: 'ocaml5200',
    erlang: 'erl2710',
    racket: 'racket8140',
    raku: 'rakutrunk',
    clean: 'cleantrunk',
    lean: 'lean4latest',
    dart: 'dart325',
    julia: 'julia1110',
    mojo: 'mojo2400',
    nix: 'nixlatest',
    hylo: 'hylotrunk',
    hook: 'hooktrunk',
    spice: 'spicetrunk',
    snowball: 'snowballtrunk',
    slang: 'slangtrunk',
    solidity: 'soljson097',
    algol68: 'algol68gtrunk',
    modula2: 'gm2142',
};

const GODBOLT_DEFAULT_OPTIONS: Record<string, string> = {
    'c++': '-O2 -std=c++23',
    c: '-O2 -std=c17',
    'objc++': '-O2',
    objc: '-O2',
    openclc: '-O2',
    c3: '',
    cuda: '-O2',
    csharp: '',
    fsharp: '',
    vb: '',
    java: '',
    kotlin: '',
    scala: '',
    clojure: '',
    rust: '-C opt-level=1',
    go: '',
    zig: '-O ReleaseSafe',
    swift: '-O',
    ada: '-O2',
    fortran: '-O2',
    d: '-O',
    pascal: '-O2',
    nim: '-d:release',
    crystal: '--release',
    odin: '-opt:speed',
    v: '-prod',
    vala: '',
    pony: '',
    carbon: '',
    cobol: '',
    python: '',
    ruby: '',
    perl: '',
    lua: '',
    javascript: '',
    typescript: '',
    haskell: '-O',
    ocaml: '',
    erlang: '',
    racket: '',
    raku: '',
    clean: '',
    lean: '',
    dart: '',
    julia: '',
    mojo: '',
    nix: '',
    hylo: '',
    hook: '',
    spice: '',
    snowball: '',
    slang: '',
    solidity: '',
    algol68: '',
    modula2: '',
};

function encodeBase64Utf8(str: string): string {
    const bytes = new TextEncoder().encode(str);
    const binString = Array.from(bytes, (byte) => String.fromCharCode(byte)).join('');
    return btoa(binString);
}

export function buildGodboltUrl(code: string, languageId: string): string {
    const compilerId = GODBOLT_DEFAULT_COMPILER[languageId];
    const options = GODBOLT_DEFAULT_OPTIONS[languageId] ?? '';

    if (!compilerId) {
        const clientState = {
            sessions: [{ id: 1, language: languageId, source: code, compilers: [], executors: [] }],
        };
        const encoded = encodeBase64Utf8(JSON.stringify(clientState));
        return `https://godbolt.org/clientstate/${encoded}`;
    }

    const clientState = {
        sessions: [
            {
                id: 1,
                language: languageId,
                source: code,
                compilers: [
                    {
                        id: compilerId,
                        options,
                        filters: {
                            intel: true,
                            demangle: true,
                            commentOnly: true,
                            directives: false,
                            labels: false,
                            trim: false,
                            binary: false,
                            binaryObject: false,
                            execute: false,
                            libraryCode: false,
                        },
                    },
                ],
                executors: [
                    {
                        compiler: {
                            id: compilerId,
                            options,
                            libs: [],
                        },
                        stdin: '',
                        stdinVisible: false,
                        args: '',
                        runtimeTools: [],
                    },
                ],
            },
        ],
    };

    const encoded = encodeBase64Utf8(JSON.stringify(clientState));
    return `https://godbolt.org/clientstate/${encoded}`;
}

